version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sonic_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://sonic:0416@db:5432/sonic_db
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./scripts:/app/scripts
      - ./out:/out
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: music-mapmap-postgres-seeded
    container_name: sonic_db
    environment:
      - POSTGRES_USER=sonic
      - POSTGRES_PASSWORD=0416
      - POSTGRES_DB=sonic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sonic_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    name: music-mapmap_postgres_data